### ISSUE TITLE
Proposed template with Sass Maps

### ISSUE THREAD

**Issue by jednano** [sprity/sprity-sass#2]
What do you think about using a template that utilizes Sass maps? This way, users can decide on their own rules and just import sprites where needed, like this:

``` scss
.foo {
  @import sprite(app, close-icon);
}
```

I wrote a template that does just this. What do you think?

``` scss
$sprites: (
{{#each layouts}}
    {{#each sprites}}
    {{cssesc name}}: (
        background-image: url('{{escimage url}}'),
        {{#if dpi}}
        dpi: {{dpi}}dpi,
        {{/if}}
        {{#if ratio}}
        ratio: {{ratio}},
        {{/if}}
        {{#each ../layout.items}}
        {{cssesc meta.name}}: (
            offset-x: -{{x}}px,
            offset-y: -{{y}}px,
            width: {{width}}px,
            height: {{height}}px
        ),
        {{/each}}
    ),
    {{/each}}
{{/each}}
);

@mixin sprite($folder-name, $image-name, $display: block) {
    $sprite: map-get($sprites, sprite-#{$folder-name});
    $background-image: map-get($sprite, background-image);

    @if map-has-key($sprite, dpi) and map-has-key($sprite, ratio) {
        $dpi: map-get($sprite, dpi);
        $ratio: map-get($sprite, ratio);
        @media (-webkit-min-device-pixel-ratio: $ratio, (min-resolution: $dpi)) {
            background-image: $background-image;
            background-size: map-get($sprite, width) map-get($sprite, height);
        }
    }
    @else {
        background-image: $background-image;
    }

    background-repeat: no-repeat;
    $image-props: map-get($sprite, $image-name);
    background-position:
        map-get($image-props, offset-x)
        map-get($image-props, offset-y)
    ;
    overflow: hidden;
    display: $display;
    width: map-get($image-props, width);
    height: map-get($image-props, height);
}

@function sprite-width($folder-name, $image-name) {
    $sprite: map-get($sprites, sprite-#{$folder-name});
    $image-props: map-get($sprite, $image-name);
    @return map-get($image-props, width);
}

@function sprite-height($folder-name, $image-name) {
    $sprite: map-get($sprites, sprite-#{$folder-name});
    $image-props: map-get($sprite, $image-name);
    @return map-get($image-props, height);
}
```

This means you can also make computations off the widths and heights, if for whatever reason you need access to those values, like so...

``` scss
.foo {
  width: sprite-width(app, close-icon);
}
```

That's just an example, of course.
